langauge: node_js
node_js:
  - 7
cache: npm
before_install:
  - npm i -g npm@6.4.1
install:
  - npm install
script:
  - npm run test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: mentorcrowd
  on:
    repo: andrewkyu/mentorcrowd
