langauge: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@10.15.3
install:
  - npm install
script:
  - npm run test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: mentorcrowd
  on:
    repo: andrewkyu/mentorcrowd
